import { jsPDF } from 'jspdf';

interface UtilityData {
  id: number;
  utility_type: string;
  amount: number;
  bill_month: string;
  due_date: string;
  paid: boolean;
  unit_number?: string;
  property_address?: string;
}

export function generateUtilityBillPDF(utility: UtilityData): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Header
  doc.setFillColor(34, 197, 94); // Green for utilities
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('UTILITY BILL', pageWidth / 2, 20, { align: 'center' });
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('RentEase Property Management', pageWidth / 2, 32, { align: 'center' });
  
  // Reset text color
  doc.setTextColor(0, 0, 0);
  
  // Bill ID and Date
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Bill ID: UB-${String(utility.id).padStart(5, '0')}`, 20, 55);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, pageWidth - 20, 55, { align: 'right' });
  
  // Utility Type Icon Header
  doc.setTextColor(34, 197, 94);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  const utilityTypeDisplay = utility.utility_type.charAt(0).toUpperCase() + utility.utility_type.slice(1);
  doc.text(utilityTypeDisplay + ' Bill', pageWidth / 2, 75, { align: 'center' });
  
  // Property Details Section
  doc.setTextColor(34, 197, 94);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('PROPERTY DETAILS', 20, 95);
  doc.setDrawColor(34, 197, 94);
  doc.line(20, 98, pageWidth - 20, 98);
  
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(11);
  
  doc.setFont('helvetica', 'bold');
  doc.text('Property:', 20, 110);
  doc.setFont('helvetica', 'normal');
  doc.text(utility.property_address || 'Not specified', 60, 110);
  
  doc.setFont('helvetica', 'bold');
  doc.text('Unit:', 20, 120);
  doc.setFont('helvetica', 'normal');
  doc.text(utility.unit_number || 'N/A', 60, 120);
  
  // Bill Details Section
  doc.setTextColor(34, 197, 94);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('BILL DETAILS', 20, 145);
  doc.line(20, 148, pageWidth - 20, 148);
  
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(11);
  
  const billData = [
    ['Utility Type:', utilityTypeDisplay],
    ['Billing Period:', utility.bill_month],
    ['Due Date:', new Date(utility.due_date).toLocaleDateString()],
    ['Status:', utility.paid ? 'PAID' : 'UNPAID'],
  ];
  
  let billY = 160;
  billData.forEach(([label, value]) => {
    doc.setFont('helvetica', 'bold');
    doc.text(label, 20, billY);
    doc.setFont('helvetica', 'normal');
    doc.text(value, 70, billY);
    billY += 12;
  });
  
  // Amount Box
  doc.setFillColor(240, 253, 244); // Light green background
  doc.roundedRect(20, 210, pageWidth - 40, 40, 5, 5, 'F');
  
  doc.setTextColor(34, 197, 94);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('TOTAL AMOUNT DUE', pageWidth / 2, 225, { align: 'center' });
  
  doc.setFontSize(24);
  doc.text(`BDT ${Number(utility.amount).toLocaleString()}`, pageWidth / 2, 242, { align: 'center' });
  
  // Payment Status
  if (utility.paid) {
    doc.setFillColor(34, 197, 94);
    doc.roundedRect(pageWidth / 2 - 30, 260, 60, 20, 3, 3, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(12);
    doc.text('PAID', pageWidth / 2, 273, { align: 'center' });
  } else {
    doc.setFillColor(239, 68, 68);
    doc.roundedRect(pageWidth / 2 - 30, 260, 60, 20, 3, 3, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(12);
    doc.text('UNPAID', pageWidth / 2, 273, { align: 'center' });
  }
  
  // Footer
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text('This document was generated by RentEase Property Management System.', pageWidth / 2, 290, { align: 'center' });
  
  // Save the PDF
  const filename = `Utility_Bill_${utilityTypeDisplay}_${utility.id}.pdf`;
  doc.save(filename);
}
