export const dummyProperties = [
  {
    id: "1",
    name: "Sunset Villa",
    address: "123 Palm Street, Miami, FL 33101",
    type: "house",
    rentAmount: 2500,
    size: "2,400 sq ft",
    availability: "occupied",
    tenantName: "John Smith",
    tenantId: "t1",
  },
  {
    id: "2",
    name: "Downtown Loft",
    address: "456 Main Avenue, New York, NY 10001",
    type: "apartment",
    rentAmount: 3200,
    size: "1,800 sq ft",
    availability: "occupied",
    tenantName: "Sarah Johnson",
    tenantId: "t2",
  },
  {
    id: "3",
    name: "Garden Apartment",
    address: "789 Oak Road, Austin, TX 78701",
    type: "apartment",
    rentAmount: 1800,
    size: "1,200 sq ft",
    availability: "available",
    tenantName: null,
    tenantId: null,
  },
  {
    id: "4",
    name: "Beach House",
    address: "321 Ocean Drive, San Diego, CA 92101",
    type: "house",
    rentAmount: 4500,
    size: "3,200 sq ft",
    availability: "occupied",
    tenantName: "Michael Brown",
    tenantId: "t3",
  },
];

export const dummyUnits = [
  {
    id: "u1",
    propertyId: "1",
    unitNumber: "Main",
    rentAmount: 2500,
    size: 2400,
    status: "Occupied",
  },
  {
    id: "u2",
    propertyId: "2",
    unitNumber: "101",
    rentAmount: 3200,
    size: 1800,
    status: "Occupied",
  },
  {
    id: "u3",
    propertyId: "3",
    unitNumber: "A",
    rentAmount: 1800,
    size: 1200,
    status: "Available",
  },
];

export const dummyTenants = [
  {
    id: "t1",
    name: "John Smith",
    email: "john.smith@email.com",
    phone: "+1 (555) 123-4567",
    propertyId: "1",
    propertyName: "Sunset Villa",
    rentAmount: 2500,
    leaseDuration: 12,
    leaseStart: "2024-01-01",
    leaseEnd: "2024-12-31",
    status: "active",
  },
  {
    id: "t2",
    name: "Sarah Johnson",
    email: "sarah.j@email.com",
    phone: "+1 (555) 234-5678",
    propertyId: "2",
    propertyName: "Downtown Loft",
    rentAmount: 3200,
    leaseDuration: 24,
    leaseStart: "2023-06-01",
    leaseEnd: "2025-05-31",
    status: "active",
  },
  {
    id: "t3",
    name: "Michael Brown",
    email: "m.brown@email.com",
    phone: "+1 (555) 345-6789",
    propertyId: "4",
    propertyName: "Beach House",
    rentAmount: 4500,
    leaseDuration: 18,
    leaseStart: "2024-03-01",
    leaseEnd: "2025-08-31",
    status: "active",
  },
];

export const dummyPayments = [
  {
    id: "p1",
    tenantId: "t1",
    tenantName: "John Smith",
    propertyId: "1",
    propertyName: "Sunset Villa",
    amount: 2500,
    status: "paid",
    dueDate: "2024-11-01",
    paymentDate: "2024-10-28",
  },
  {
    id: "p2",
    tenantId: "t2",
    tenantName: "Sarah Johnson",
    propertyId: "2",
    propertyName: "Downtown Loft",
    amount: 3200,
    status: "paid",
    dueDate: "2024-11-01",
    paymentDate: "2024-11-01",
  },
  {
    id: "p3",
    tenantId: "t3",
    tenantName: "Michael Brown",
    propertyId: "4",
    propertyName: "Beach House",
    amount: 4500,
    status: "due",
    dueDate: "2024-11-15",
    paymentDate: null,
  },
  {
    id: "p4",
    tenantId: "t1",
    tenantName: "John Smith",
    propertyId: "1",
    propertyName: "Sunset Villa",
    amount: 2500,
    status: "overdue",
    dueDate: "2024-10-01",
    paymentDate: null,
  },
];

export const dummyUtilities = [
  {
    id: "u1",
    tenantId: "t1",
    tenantName: "John Smith",
    propertyId: "1",
    propertyName: "Sunset Villa",
    utilityType: "electricity",
    amount: 150,
    status: "paid",
    billingDate: "2024-10-15",
  },
  {
    id: "u2",
    tenantId: "t2",
    tenantName: "Sarah Johnson",
    propertyId: "2",
    propertyName: "Downtown Loft",
    utilityType: "water",
    amount: 80,
    status: "unpaid",
    billingDate: "2024-11-01",
  },
  {
    id: "u3",
    tenantId: "t3",
    tenantName: "Michael Brown",
    propertyId: "4",
    propertyName: "Beach House",
    utilityType: "gas",
    amount: 120,
    status: "paid",
    billingDate: "2024-10-20",
  },
  {
    id: "u4",
    tenantId: "t1",
    tenantName: "John Smith",
    propertyId: "1",
    propertyName: "Sunset Villa",
    utilityType: "internet",
    amount: 100,
    status: "unpaid",
    billingDate: "2024-11-05",
  },
];

export const rentTrendsData = [
  { month: "May", collected: 8500, expected: 10200 },
  { month: "Jun", collected: 10200, expected: 10200 },
  { month: "Jul", collected: 9800, expected: 10200 },
  { month: "Aug", collected: 10200, expected: 10200 },
  { month: "Sep", collected: 7700, expected: 10200 },
  { month: "Oct", collected: 10200, expected: 10200 },
];

export const paymentStatusData = [
  { name: "Paid", value: 65, fill: "hsl(var(--success))" },
  { name: "Due", value: 20, fill: "hsl(var(--accent))" },
  { name: "Overdue", value: 15, fill: "hsl(var(--destructive))" },
];

export const testimonials = [
  {
    name: "Jennifer Wilson",
    role: "Property Owner",
    content: "RentEase has transformed how I manage my properties. Everything is organized and accessible in one place.",
    rating: 5,
  },
  {
    name: "David Martinez",
    role: "Landlord",
    content: "The payment tracking feature saves me hours every month. Highly recommended for any property manager!",
    rating: 5,
  },
  {
    name: "Lisa Anderson",
    role: "Real Estate Investor",
    content: "Professional, intuitive, and reliable. RentEase is exactly what I needed to scale my rental business.",
    rating: 5,
  },
];
